### ISSUE TITLE
Please check your device and try again, yet writes to eeprom

### ISSUE THREAD

**Issue by koogar** [ManyKeyOrg/manykey_writer#4]
Under Windows10 (64) I get the following error box

"An Error Occured
Please check your device and try again"

When the error box is closed it does pop up the "Successfully Wrote Keys" box, and it has indeed wrote the correct data to the eeprom

great work BTW :)

Thanks 
Rupert

**Comment by epbarger** [comment]
That's odd... I'll take a look. The error handling is a bit barebones at the moment, so I'm not surprised there are some issues.

Glad you like the project!
